### ISSUE TITLE
general question

### ISSUE THREAD

**Issue by illuminate3** [TypiCMS/Core#3]
Hi!

Thank you for all your work!
I've been going through your menu / menulink packages and really have been learning a lot from them,

I do have a question: in you repositories you use ...

```
        $query = $this->make($with);

        if (! $all) {
            $query->online();
        }
```

I do not understand the `online()` part. 
Where is this coming from?

Thanks!

**Comment by sdebacker** [comment]
It's a query scope defined in Base model.
http://laravel.com/docs/5.1/eloquent#query-scopes

**Comment by illuminate3** [comment]
Thanks!
