### ISSUE TITLE
Laravel 5.2.16 breaks API

### ISSUE THREAD

**Issue by eahrold** [TypiCMS/Core#37]
Not sure if you've ran composer update lately but after updating from `laravel/framework v5.2.14 -> v5.2.16` I started getting this exception...

https://gist.github.com/eahrold/e60a70206696b772cf5e

In composer.json explicitly declaring `"laravel/framework": "5.2.14",` fixes the issue

**Comment by sdebacker** [comment]
No problem at my side. I see that you have Dingo/api.

**Comment by eahrold** [comment]
I thought that may have caused the issue, but I removed it when trying to diagnose (then added it back).

Anyway here's a screen cast of the issue I'm seeing, not sure if there's anything useful. 

https://www.dropbox.com/s/t3zjx8faf0wsyxo/TypiCMS-Laravel-5.14-error.mov?dl=0

**Comment by sdebacker** [comment]
ok I see, I also have the bug.

**Comment by sdebacker** [comment]
https://laracasts.com/discuss/channels/laravel/bug-in-the-latest-api-throttle-middleware

**Comment by sdebacker** [comment]
It's a known bug that will be squashed by Laravel 5.2.17: https://github.com/laravel/framework/commit/0718ac86e38d625812fa80c73bde8539ae9967fe

**Comment by sdebacker** [comment]
@eahrold Thanks for pointing it out!
