### ISSUE TITLE
FileObserver saving() method

### ISSUE THREAD

**Issue by eahrold** [TypiCMS/Core#48]
I'm not sure if you can replicate this at all, but for me, with most modules, FileObserver()'s `saving` method is getting called erratically. 

`updated` and `deleted` are getting called consistently, just not `saving` for some reason.
I tried disabling caching, but that didn't have any noticeable effect. 

For example with the Pages module, `saving` isn't called when content from  the wysiwyg editor is changed, but it is called when the `no_cache` val is changed.
And yet `saving` _is_ called when the sort order of the pages is altered (from the admin index).

I'm stumped. Any advice would be appreciated.

Thanks.

Here's a quick video of what I'm seeing..
https://www.dropbox.com/s/yp60e3rek40mm3x/ObserverNotObserving.mov?dl=0

**Comment by sdebacker** [comment]
I will look at this now.

**Comment by sdebacker** [comment]
In fact saving is only called when untranslatable fields has changed (like position when sorting, no_cahce, etc.). For translated fields, saved and updated are called but not saving. That's how the package https://github.com/dimsav/laravel-translatable works.

**Comment by eahrold** [comment]
Ok, that actually makes perfect sense.

I only discovered this because I didn't have the correct file `$fieldname` in in my model's `$attachments` array. I fixed that  but ended up getting into a condition where the db col was `delete`, and since all other items were translatable the clean-up in the FileObserver never happened.
Pretty fringe case, and my err.

Thanks for looking into this.
