### ISSUE TITLE
Composer keeps publishing the core.

### ISSUE THREAD

**Issue by eahrold** [TypiCMS/Core#68]
Wasn't sure exactly where to put this issue, figured here was as good a place as any. 
I've published the Core module, which on the initial publish removed it from the vendor folder, as expected. But now when I run composer update, or add another package, it actually reinstalls the core package in the vendor folder, which ends up taking precedence over the published version.

I suspect it's due to the other modules having the "Core" required, and composer not detecting the published "core".

**Comment by sdebacker** [comment]
It's currently a limitation of TypiCMS, if you want to publish Core, you will have to publish every other modules needed for your project.
