### ISSUE TITLE
Call to undefined method Maatwebsite\Sidebar\SidebarManager::build() (View: */resources/views/vendor/core/admin/master.blade.php) 

### ISSUE THREAD

**Issue by endriupix** [TypiCMS/Core#93]
Hi,
after last composer update i have this error in every admin views (I installed TypiCms this morning and it worked before update)

Thanks

**Comment by sdebacker** [comment]
Hello, thanks for reporting, it's now fixed.

**Comment by sdebacker** [comment]
Just run `composer update`.
